var codes = [
"ALTM",
"AUXS",
"BERT",
"BOM1",
"BOM2",
"BOM3",
"BSUB",
"CENT",
"CIVL",
"CRES",
"CSCB",
"CSSB",
"CSTL",
"CUGR",
"DMSF",
"EECH",
"EMGT",
"ENRL",
"FULT",
"GBMB",
"GSVB",
"HARH",
"HASM",
"HAVC",
"HPRF",
"HSSB",
"HYFS",
"IDEB",
"KEMB",
"KSDC",
"LIBR",
"MCNU",
"MURY",
"NORW",
"NUCR",
"PCRA",
"PHYS",
"PKRH",
"PSB1",
"PWRP",
"RAIC",
"RESL",
"RLAB",
"RMER",
"RPDC",
"RSC1",
"RSC2",
"RSTE",
"SBMC",
"SCHR",
"STHC",
"STRH",
"TDEC",
"TFAA",
"TJRH",
"TMPR",
"TMYH",
"U710",
"UCOM"]

var buildings = [
"Altman Hall",
"Auxiliary Services Building",
"James E. Bertlesmeyer Hall",
"Bureau of Mines Building #1",
"Bureau of Mines Building #2",
"Bureau of Mines Building #3",
"Baptist Student Union Building",
"Centennial Hall",
"Butler-Carlton Civil Engineering Hall",
"Computer Science Building",
"Chancellor's Residence",
"Campus Support Facility",
"Castleman Hall",
"Custodial & Landscape Services Building",
"Dangerous Materials Storage Facility",
"Emerson Electric Company Hall",
"Engineering Management Building",
"Engineering Research Laboratory Building",
"Fulton Hall",
"Gale Bullman Building",
"General Services Building",
"Harris Hall",
"Hasselmann Alumni House",
"Havener Center",
"Hy Point Building",
"Humanities & Social Sciences Building",
"Hydrogen Filling Station",
"Interdisciplinary Engineering Building",
"Kennedy Experimental Mine Building",
"Kummer Student Design Center",
"Curtis Laws Wilson Library",
"V.H. McNutt Hall",
"Murray Apartment Building",
"Norwood Hall",
"Nuclear Reactor",
"PCRMC Annex Building",
"Physics Building",
"Parker Hall",
"Pine Building",
"Power Plant",
"Student Recreation & Intramural Center",
"Campus Housing and Dining Services",
"Rolla Building",
"Rock Mechanics & Explosives Research Center",
"South Central Regional Professional Development Center",
"Residential Commons 1",
"Residential Commons 2",
"Rolla Suites South Building #1",
"Southwestern Bell Cultural Center",
"Schrenk Hall",
"Student Health Complex",
"Straumanis-James Hall",
"Technology Development Center",
"Temporary Facility A",
"Thomas Jefferson Residence Hall",
"Temporary Research Facility",
"Toomey Hall",
"710 University Drive Building",
"University Commons"
]
